### ISSUE TITLE
memory usage of _ad_convert_type

### ISSUE THREAD

**Issue by GregorWautischer** [firedrakeproject/firedrake#2699] opened 2023-01-02 12:42 UTC
Hi all! When trying to use the ROLSolver a while ago I ran into memory problems. I originally posted an issue [here ](https://github.com/dolfin-adjoint/pyadjoint/issues/77) that is now closed. I was now able to trace those back to the method _ad_convert_type of the FunctionMixin class (firedrake/adjoint/function.py). To illustrate the problem consider the following example:

```
from firedrake import *
from firedrake_adjoint import *

mesh = UnitCubeMesh(100,100,10)

VFS = VectorFunctionSpace(mesh, "CG", 1)

m = interpolate(Constant((1., 0., 0.)), VFS)
for i in range(100):
    m = m._ad_convert_type(m, {"riesz_representation": "L2"})
```

While running this will steadily increase memory usage. The memory problem can be avoided by using a custom "riesz_representation" like (that also is much faster of course):

```
from firedrake import *
from firedrake_adjoint import *

mesh = UnitCubeMesh(100,100,10)

VFS = VectorFunctionSpace(mesh, "CG", 1)

m = interpolate(Constant((1., 0., 0.)), VFS)

u = TrialFunction(VFS)
v = TestFunction(VFS)
M = assemble(inner(u, v)*dx)
solver = LinearSolver(M)

def sol(x):
    ret = Function(VFS)
    solver.solve(ret, x)
    return ret

for i in range(100):
    m._ad_convert_type(m, {"riesz_representation": sol})

```

Therefore I guess the problem is that something is not cleaned up correctly. 

Regarding my original problem with the ROLSolver, the above fix does not solve my problem. This is since eventhoug a custom "riesz_representation" can be passed to the ROLSoler as parameter "inner_product", the execution fails since the "inner_product" is also passed to the method _ad_dot of the FunctionMixin class that throws an error when receiving something else then "l2", "L2" or "H1" as "riesz representation".

Thanks for looking into this and happy new year,

Gregor

**Comment by dham** [comment] 2023-01-03 09:29
@JDBetteridge looks like we're leaking solvers...

**Comment by JDBetteridge** [comment] 2023-01-03 15:03
Thanks for the MFE @GregorWautischer ! I'm aware there are a few bugs introduced with all of the changes surrounding the garbage collector and comm duplication. The issue is fixed in [this PR](https://github.com/firedrakeproject/firedrake/pull/2674), which will hopefully be ready to merge next week.

**Comment by GregorWautischer** [comment] 2023-01-04 13:45
Thanks for the response and happy to help. Good to know that there already is a fix.

However, what about the ROLSolver issue when using a custom "inner_product"? Should I open a new issue regarding that (possibly at the pyadjoint repo)?

**Comment by wence-** [comment] 2023-01-09 14:25
> However, what about the ROLSolver issue when using a custom "inner_product"? Should I open a new issue regarding that?

Yes please.

**Closed** 2023-01-18 16:47 UTC
