### ISSUE TITLE
BUG: Memory growth with repeated assign calls when firedrake.adjoint is imported 

### ISSUE THREAD

**Issue by enricofacca** [firedrakeproject/firedrake#3133] opened 2023-09-29 09:11 UTC
**Describe the bug**
I experimented an increased memory usage any time firedrake.adjoint or firedrake_adjoint (deprecated) is imported.
Here below a minimal working example showing the issue. Similar issues are mentioned in #2866 and #3069 but in more complicated usage of the adjoint module, which I'll need to do as well. It seems to me that just importing the adjoint module causes some memory mismanagement that I not able to understand.
```
from firedrake import *
from firedrake.adjoint import *
continue_annotation()
import gc
from firedrake.petsc import PETSc
from memory_profiler import profile
    
@profile
def main():
    mesh = UnitSquareMesh(300,200)
    x = SpatialCoordinate(mesh)
    V = FunctionSpace(mesh, 'DG', 0)
    f = Function(V)
    g = Function(V)

    for i in range(1000):
        print(i)
        f.interpolate(x[0]*x[1]+i)
        g.assign(f+i)
        gc.collect()
        PETSc.garbage_cleanup(PETSc.COMM_SELF)      

if __name__ == '__main__':
    main()
```

I run this code using the memory profiler.
```
mprof run python memory_MWE.py
```
The image reports the memory usage with (black line) and without (without) importing the adjoint module.
![image](https://github.com/firedrakeproject/firedrake/assets/46008578/fdfefad0-c239-45b5-834a-08523a43c2cc)

I included the commands  
```
gc.collect()
PETSc.garbage_cleanup(PETSc.COMM_SELF)      
```
as suggested in #2866 , but does the memory usage keeps increasing.

**Environment:**
 - OS: Ubuntu 18.04 (firedrake is running within a Docker env)
 - Python version: 3.10.12
 - Output of `firedrake-status`
Firedrake Configuration:
    package_manager: False
    minimal_petsc: False
    mpicc: /home/firedrake/petsc/packages/bin/mpicc
    mpicxx: /home/firedrake/petsc/packages/bin/mpicxx
    mpif90: /home/firedrake/petsc/packages/bin/mpif90
    mpiexec: /home/firedrake/petsc/packages/bin/mpiexec
    disable_ssh: True
    honour_petsc_dir: True
    with_parmetis: False
    slepc: True
    honour_pythonpath: False
    opencascade: False
    tinyasm: True
    torch: cpu
    petsc_int_type: int32
    cache_dir: /home/firedrake/firedrake/.cache
    complex: False
    remove_build_files: False
    with_blas: None
    netgen: True
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: default
    PETSC_DIR: /home/firedrake/petsc
Status of components:
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|FEMlium             |main                          |cc2c7a3   |True      |
|FInAT               |master                        |f493084   |True      |
|Irksome             |master                        |bd4a77d   |True      |
|PyOP2               |master                        |8e4ad930  |False     |
|TinyASM             |master                        |015a89a   |True      |
|fiat                |master                        |e440a06   |True      |
|firedrake           |master                        |ca687792e |False     |
|gusto               |main                          |b51dc22f  |True      |
|h5py                |firedrake                     |6cc4c912  |True      |
|icepack             |master                        |d134d25   |True      |
|libspatialindex     |master                        |4768bf3   |True      |
|libsupermesh        |master                        |dbe226b   |True      |
|loopy               |main                          |8158afdb  |True      |
|pyadjoint           |master                        |78b3bd6   |True      |
|pytest-mpi          |main                          |a478bc8   |True      |
|thetis              |master                        |9832fc88  |True      |
|tsfc                |master                        |47c1324   |True      |
|ufl                 |master                        |cf66c4b3  |True      |
---------------------------------------------------------------------------

**Comment by connorjward** [comment] 2023-09-29 09:17
What happens if you include the line
```py
PETSc.garbage_cleanup(mesh._comm)
```
You are not calling `solve` anywhere so PETSc objects on the "normal" communicator are not getting cleaned up.

Note that if my hunch is right, and you are running in serial, this will go away as a problem as soon as we update our PETSc fork (which we should do in the next few days).

**Comment by enricofacca** [comment] 2023-09-29 09:35
Yes, I am running in serial.
I included 
```
PETSc.garbage_cleanup(mesh._comm)
```


> What happens if you include the line
> 
> ```python
> PETSc.garbage_cleanup(mesh._comm)
> ```
I included but the memory keeps increasing.
> 
> You are not calling `solve` anywhere so PETSc objects on the "normal" communicator are not getting cleaned up.
> 
> Note that if my hunch is right, and you are running in serial, this will go away as a problem as soon as we update our PETSc fork (which we should do in the next few days).
Yes, I am running in serial.

**Comment by Ig-dolci** [comment] 2023-09-29 09:51
The increase in memory usage when you import `firedrake.adjoint` and enable the `continue_annotate` is expected because the operations within the `for` are stored in memory. If you are not importing `firedrake.adjoint`  and activating the `continue_annotate`, there will not be any storage of operations. That is the reason for the observed difference in memory usage.

**Comment by enricofacca** [comment] 2023-09-29 11:29
> The increase in memory usage when you import `firedrake.adjoint` and enable the `continue_annotate` is expected because the operations within the `for` are stored in memory. If you are not importing `firedrake.adjoint` and activating the `continue_annotate` (without adjoint), there will not be any storage of operations. That is the reason for the observed difference in memory usage.

Thanks for the clarifications. I included continue_annotate() just following the warning raised when import firedrake_adjoint is used. Removing it solves the memory issues. However, if try to run the following code,
(where I use some functionality of the adjoint module like ReducedFunctional)
```
from firedrake import *
from firedrake.adjoint import *
import gc
from firedrake.petsc import PETSc
from memory_profiler import profile

def compute_derivative_reduced(f,d):
    J = assemble(f*dx)
    J_red = ReducedFunctional(J, Control(f))
    d = J_red.derivative()

@profile
def main():
    mesh = UnitSquareMesh(300,200)
    x = SpatialCoordinate(mesh)
    V = FunctionSpace(mesh, 'DG', 0)
    f = Function(V)
    g = Function(V)
    d = Function(V)
    
    for i in range(100):
        print(i)
        f.interpolate(x[0]*x[1]+i)
        g.assign(f+i)
        compute_derivative_reduced(f,d)
        gc.collect()
        PETSc.garbage_cleanup(PETSc.COMM_SELF)      
        PETSc.garbage_cleanup(mesh._comm)

if __name__ == '__main__':
    main()
```
I received the following error
___
Traceback (most recent call last):
  File "/home/firedrake/shared/tests/memory_MWE.py", line 31, in <module>
    main()
  File "/home/firedrake/firedrake/lib/python3.10/site-packages/memory_profiler.py", line 1188, in wrapper
    val = prof(func)(*args, **kwargs)
  File "/home/firedrake/firedrake/lib/python3.10/site-packages/memory_profiler.py", line 761, in f
    return func(*args, **kwds)
  File "/home/firedrake/shared/tests/memory_MWE.py", line 25, in main
    compute_derivative_reduced(f,d)
  File "/home/firedrake/shared/tests/memory_MWE.py", line 9, in compute_derivative_reduced
    J_red = ReducedFunctional(J, Control(f))
  File "/home/firedrake/firedrake/src/pyadjoint/pyadjoint/reduced_functional.py", line 78, in __init__
    raise TypeError("Functional must be an OverloadedType.")
TypeError: Functional must be an OverloadedType.
___

If replace `from firedrake.adjoint import * ` with   `from firedrake_adjoint import * ` the code works but the memory issue appears again. This happens even if the function compute_derivative_reduced.

In my code, I need to use the ReducedFunctional operator for something more complicated than `H=assemble(f*dx)`, but I thought (maybe I am wrong) that it would be simpler to present.

Thank you again for the help.

**Comment by connorjward** [comment] 2023-09-29 12:10
It is intrinsic to how the adjoint is implemented that memory leaks occur. When annotation is turned on (necessary for the adjoint to work) then intermediate results are recorded to a "tape".

From the [pyadjoint docs](https://pyadjoint.org/documentation/index.html):
>  In order to compute the adjoints we must somehow remember all the operations performed in the forward computations, and either remember or recompute the intermediate variables.

**Comment by dham** [comment] 2023-09-29 13:00
> It is intrinsic to how the adjoint is implemented that memory leaks occur. 

It's stronger than this. It's intrinsic to the maths of the adjoint, it's not our implementation that's at fault.

**Comment by enricofacca** [comment] 2023-09-29 16:13
Thank you very much for the clarifications. 

For sake of completeness I include a block of code more closely related to the usage of the adjoint module. I took this[ fenics example ](http://www.dolfin-adjoint.org/en/latest/documentation/custom_functions.html) from pyadjoint and adapted to firedrake.
Here the memory problems are really confusing to me.

```
from firedrake import *
from firedrake_adjoint import *

import gc
from firedrake.petsc import PETSc
from memory_profiler import profile

from pyadjoint import Block
from pyadjoint.overloaded_function import overload_function

from numpy.random import rand

def normalise(func):
    vec = func.vector()
    with func.dat.vec as vec:
        normalised_vec = vec.copy()
        n = normalised_vec.norm()
        normalised_vec.scale(1/n)
    return Function(func.function_space(), normalised_vec)

backend_normalise = normalise

class NormaliseBlock(Block):
    def __init__(self, func, **kwargs):
        super(NormaliseBlock, self).__init__()
        self.kwargs = kwargs
        self.add_dependency(func)

    def evaluate_adj_component(self, inputs, adj_inputs, block_variable, idx, prepared=None):
        adj_input = adj_inputs[0]
        x = inputs[idx]
        out = Function(x.function_space())
        with x.dat.vec as x_vec, adj_input.dat.vec as y_vec, out.dat.vec as out_vec:
            inv_xnorm = 1.0 / x_vec.norm()
            prod = x_vec.dot(y_vec)
            out_vec = inv_xnorm * y_vec - inv_xnorm ** 3 * prod * x_vec
        return out

    def recompute_component(self, inputs, block_variable, idx, prepared):
        return backend_normalise(inputs[0])

normalise = overload_function(normalise, NormaliseBlock)

def compute_derivative_reduced(f,d):
    J = assemble(normalise(f)*dx)
    J_red = ReducedFunctional(J, Control(f))
    d = J_red.derivative()


@profile
def main():
    mesh = UnitSquareMesh(200,200)
    x = SpatialCoordinate(mesh)
    V = FunctionSpace(mesh, 'DG', 0)
    f = Function(V)
    g = Function(V)
    d = Function(V)

    f.assign(2.0)
    g.vector()[:] = rand(g.vector().local_size())
    
    fnorm = normalise(f)
    J = assemble(fnorm*dx)   
    taylor_test(ReducedFunctional(J, Control(f)), f, g)
    
    for i in range(100):
        print(i)
        
        f.interpolate(x[0]*x[1]+i)
        g.assign(f+i)
        compute_derivative_reduced(f,d)
        
        gc.collect()
        PETSc.garbage_cleanup(PETSc.COMM_SELF)      
        PETSc.garbage_cleanup(mesh._comm)

if __name__ == '__main__':
    main()
```

If run the script, the memory profiler gives me these results
```
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    50    284.4 MiB    284.4 MiB           1   @profile
    51                                         def main():
    52    306.0 MiB     21.6 MiB           1       mesh = UnitSquareMesh(200,200)
    53    306.0 MiB      0.0 MiB           1       x = SpatialCoordinate(mesh)
    54    342.0 MiB     36.1 MiB           1       V = FunctionSpace(mesh, 'DG', 0)
    55    342.0 MiB      0.0 MiB           1       f = Function(V)
    56    342.0 MiB      0.0 MiB           1       g = Function(V)
    57    342.0 MiB      0.0 MiB           1       d = Function(V)
    58                                         
    59    343.9 MiB      1.9 MiB           1       f.assign(2.0)
    60    345.3 MiB      1.4 MiB           1       g.vector()[:] = rand(g.vector().local_size())
    61                                             
    62    346.1 MiB      0.8 MiB           1       fnorm = normalise(f)
    63    349.0 MiB      2.9 MiB           1       J = assemble(fnorm*dx)   
    64    366.6 MiB     17.6 MiB           1       taylor_test(ReducedFunctional(J, Control(f)), f, g)
    65                                             
    66    614.3 MiB      0.0 MiB         101       for i in range(100):
    67    611.8 MiB      0.0 MiB         100           print(i)
    68                                                 
    69    612.0 MiB     22.9 MiB         100           f.interpolate(x[0]*x[1]+i)
    70    612.0 MiB      0.0 MiB         100           g.assign(f+i)
    71    614.3 MiB    224.9 MiB         100           compute_derivative_reduced(f,d)
    72                                                 
    73    614.3 MiB      0.0 MiB         100           gc.collect()
    74    614.3 MiB      0.0 MiB         100           PETSc.garbage_cleanup(PETSc.COMM_SELF)      
    75    614.3 MiB      0.0 MiB         100           PETSc.garbage_cleanup(mesh._comm)

```
If I just comment line 71, where I use ReducedFunctional I get the following


```
Filename: /home/firedrake/shared/tests/normalise_overloaded.py
Line #    Mem usage    Increment  Occurrences   Line Contents
=============================================================
    50    284.4 MiB    284.4 MiB           1   @profile
    51                                         def main():
    52    306.2 MiB     21.8 MiB           1       mesh = UnitSquareMesh(200,200)
    53    306.2 MiB      0.0 MiB           1       x = SpatialCoordinate(mesh)
    54    342.0 MiB     35.8 MiB           1       V = FunctionSpace(mesh, 'DG', 0)
    55    342.0 MiB      0.0 MiB           1       f = Function(V)
    56    342.0 MiB      0.0 MiB           1       g = Function(V)
    57    342.0 MiB      0.0 MiB           1       d = Function(V)
    58                                         
    59    344.0 MiB      2.0 MiB           1       f.assign(2.0)
    60    345.4 MiB      1.4 MiB           1       g.vector()[:] = rand(g.vector().local_size())
    61                                             
    62    346.2 MiB      0.8 MiB           1       fnorm = normalise(f)
    63    349.3 MiB      3.1 MiB           1       J = assemble(fnorm*dx)   
    64    366.8 MiB     17.5 MiB           1       taylor_test(ReducedFunctional(J, Control(f)), f, g)
    65                                             
    66    487.3 MiB      0.0 MiB         101       for i in range(100):
    67    486.0 MiB      0.0 MiB         100           print(i)
    68                                                 
    69    486.3 MiB     28.5 MiB         100           f.interpolate(x[0]*x[1]+i)
    70    487.3 MiB     91.9 MiB         100           g.assign(f+i)
    71                                                 #compute_derivative_reduced(f,d)
    72                                                 
    73    487.3 MiB      0.1 MiB         100           gc.collect()
    74    487.3 MiB      0.0 MiB         100           PETSc.garbage_cleanup(PETSc.COMM_SELF)      
    75    487.3 MiB      0.0 MiB         100           PETSc.garbage_cleanup(mesh._comm)
```

**Comment by connorjward** [comment] 2023-10-10 09:48
@enricofacca can this issue now be closed?

**Comment by enricofacca** [comment] 2023-10-10 14:45
> @enricofacca can this issue now be closed?

I found out that a combination of tape.clear_tape() and PETSc.garbage_cleanup(mesh._comm) solves the memory issue.
None of then seems to work alone. Honestly, I have no idea what I am doing (I will appreciate any clarification on that), but it worked out to me.

```
import firedrake as fd
import firedrake.adjoint as fire_adj
fire_adj.continue_annotation()
from firedrake.petsc import PETSc

from pyadjoint import Block
from pyadjoint.overloaded_function import overload_function
from numpy.random import rand

from memory_profiler import profile

def normalise(func):
    with func.dat.vec as vec:
        n = vec.norm()
        normalised_vec = vec.copy()
        normalised_vec.scale(1/n)
    return fd.Function(func.function_space(), normalised_vec)

backend_normalise = normalise

class NormaliseBlock(Block):
    def __init__(self, func, **kwargs):
        super(NormaliseBlock, self).__init__()
        self.kwargs = kwargs
        self.add_dependency(func)

    def evaluate_adj_component(self, inputs, adj_inputs, block_variable, idx, prepared=None):
        adj_input = adj_inputs[0]
        x = inputs[idx]
        with x.dat.vec as x_vec, adj_input.dat.vec as y_vec:
            inv_xnorm = 1.0 / x_vec.norm()
            prod = x_vec.dot(y_vec)
            out_vec = inv_xnorm * y_vec - inv_xnorm ** 3 * prod * x_vec
        return fd.Function(x.function_space(), out_vec)

    def recompute_component(self, inputs, block_variable, idx, prepared):
        return backend_normalise(inputs[0])

normalise = overload_function(normalise, NormaliseBlock)

def compute_derivative_reduced(f):
    fnorm = normalise(f)
    J = fd.assemble(fnorm * fd.dx)
    J_red = fire_adj.ReducedFunctional(J, fire_adj.Control(f))
    d = J_red.derivative()
    with d.dat.vec as d_vec:
        print(d_vec.norm())
   
@profile
def main():
    mesh = fd.UnitSquareMesh(200,200)
    x = fd.SpatialCoordinate(mesh)
    V = fd.FunctionSpace(mesh, 'DG', 0)
    f = fd.Function(V)
    g = fd.Function(V)
    
    f.assign(2.0)
    g.vector()[:] = rand(g.vector().local_size())
    
    fnorm = normalise(f)
    J = fd.assemble(fnorm * fd.dx)
    J_red = fire_adj.ReducedFunctional(J, fire_adj.Control(f))   
    fire_adj.taylor_test(J_red, f, g)

    tape = fire_adj.get_working_tape()
    tape.clear_tape()
    for i in range(200):
        print(i)
        f.interpolate(x[0]*x[1]+i)
        g.assign(f+i)
        compute_derivative_reduced(f)
        tape.clear_tape()
        PETSc.garbage_cleanup(mesh._comm)  
        
if __name__ == '__main__':
    main()
```

Output of firedrake-status
```
/home/firedrake/firedrake/bin/firedrake-status:4: DeprecationWarning: pkg_resources is deprecated as an API. See https://setuptools.pypa.io/en/latest/pkg_resources.html
  __import__('pkg_resources').require('firedrake==0.13.0+5857.gca687792e')
Firedrake Configuration:
    package_manager: False
    minimal_petsc: False
    mpicc: /home/firedrake/petsc/packages/bin/mpicc
    mpicxx: /home/firedrake/petsc/packages/bin/mpicxx
    mpif90: /home/firedrake/petsc/packages/bin/mpif90
    mpiexec: /home/firedrake/petsc/packages/bin/mpiexec
    disable_ssh: True
    honour_petsc_dir: True
    with_parmetis: False
    slepc: True
    packages: ['git+ssh://github.com/FEMlium/FEMlium.git@main#egg=FEMlium', 'git+ssh://github.com/firedrakeproject/Irksome.git#egg=Irksome', 'git+ssh://github.com/firedrakeproject/gusto.git@main#egg=gusto', 'git+ssh://github.com/firedrakeproject/Irksome.git#egg=Irksome', 'git+ssh://github.com/firedrakeproject/gusto.git@main#egg=gusto', 'git+ssh://github.com/icepack/icepack.git#egg=icepack', 'git+ssh://github.com/FEMlium/FEMlium.git@main#egg=FEMlium', 'git+ssh://github.com/thetisproject/thetis#egg=thetis', 'git+ssh://github.com/icepack/icepack.git#egg=icepack', 'git+ssh://github.com/thetisproject/thetis#egg=thetis']
    honour_pythonpath: False
    opencascade: False
    tinyasm: True
    torch: cpu
    petsc_int_type: int32
    cache_dir: /home/firedrake/firedrake/.cache
    complex: False
    remove_build_files: False
    with_blas: None
    netgen: True
Additions:
    None
Environment:
    PYTHONPATH: None
    PETSC_ARCH: default
    PETSC_DIR: /home/firedrake/petsc
Status of components:
---------------------------------------------------------------------------
|Package             |Branch                        |Revision  |Modified  |
---------------------------------------------------------------------------
|FEMlium             |main                          |cc2c7a3   |True      |
|FInAT               |master                        |f493084   |True      |
|Irksome             |master                        |bd4a77d   |True      |
|PyOP2               |master                        |8e4ad930  |False     |
|TinyASM             |master                        |015a89a   |True      |
|fiat                |master                        |e440a06   |True      |
|firedrake           |master                        |ca687792e |False     |
|gusto               |main                          |b51dc22f  |True      |
|h5py                |firedrake                     |6cc4c912  |True      |
|icepack             |master                        |d134d25   |True      |
|libspatialindex     |master                        |4768bf3   |True      |
|libsupermesh        |master                        |dbe226b   |True      |
|loopy               |main                          |8158afdb  |True      |
|pyadjoint           |master                        |78b3bd6   |True      |
|pytest-mpi          |main                          |a478bc8   |True      |
|thetis              |master                        |9832fc88  |True      |
|tsfc                |master                        |47c1324   |True      |
|ufl                 |master                        |cf66c4b3  |True      |
---------------------------------------------------------------------------

```

**Comment by enricofacca** [comment] 2023-10-10 15:44
> Running `tape.clear_tape()` will completely destroy the adjoint capabilities of your program. It "solves" the memory leak because it is dropping data crucial to computing the adjoint later on.

Thus it is not possible to "clean" the memory after the computation of the gradient is done?

**Comment by JDBetteridge** [comment] 2023-10-10 15:47
The memory used by the adjoint is cleaned up at Python shutdown.

Perhaps you could explain a little more about your actual use case and how memory usage is affecting that and maybe we will be able to supply a resolution.

**Comment by ReubenHill** [comment] 2023-10-10 16:17
> > Running `tape.clear_tape()` will completely destroy the adjoint capabilities of your program. It "solves" the memory leak because it is dropping data crucial to computing the adjoint later on.
> 
> Thus it is not possible to "clean" the memory after the computation of the gradient is done?

Doesn't running `tape.clear_tape()` after you've computed the gradient do that for you?

**Comment by connorjward** [comment] 2023-10-10 16:31
> > Running `tape.clear_tape()` will completely destroy the adjoint capabilities of your program. It "solves" the memory leak because it is dropping data crucial to computing the adjoint later on.
> 
> Thus it is not possible to "clean" the memory after the computation of the gradient is done?

I think I may have been overly hasty in reading your code. If your objective is to have some sort of "outer loop" calculation where you compute the adjoint repeatedly then clearing the tape between runs is the right thing to do I am fairly sure. As @JDBetteridge said, it would be helpful to understand your use case better.

I think it would be best to close this issue - the memory consumption is a feature not a bug - and create a GitHub discussion instead.

**Closed** 2023-10-11 09:53 UTC
Labels: bug
