### ISSUE TITLE
KSP objects not being destroyed after derivative calls

### ISSUE THREAD

**Issue by angus-g** [firedrakeproject/firedrake#2671] opened 2022-12-06 03:32 UTC
I have a [simple reproducing case](https://gist.github.com/angus-g/8d94eea2260cbab50af503e9855d4367) which sets up a problem, solves it forwards, then calls `reduced_functional.derivative()` several times. Running this case (on two ranks) and inspecting the total number of objects collected in `PETSc.garbage_view(comm=mesh.comm)` shows an increase of 20 KSP objects (one per forward timestep), for each derivative call:
```
Rank 0:: Total entries: 22
Rank 0:: Total entries: 42
Rank 0:: Total entries: 62
Rank 0:: Total entries: 82
Rank 0:: Total entries: 102
Rank 0:: Total entries: 122
Rank 0:: Total entries: 142
Rank 0:: Total entries: 162
Rank 0:: Total entries: 182
Rank 0:: Total entries: 202
```

However, changing the communicator used for the call to `PETSc.garbage_cleanup()` after the solve seems to address this issue. Namely, moving from the internal `self._problem.u.function_space().mesh()._comm` to `self._problem.u.function_space().mesh().comm`:
https://github.com/firedrakeproject/firedrake/blob/a16e3a51dbd22890bda3465ea1519680b55b93de/firedrake/variational_solver.py#L284-L286

With this change, the number of KSP objects stays constant:
```
Rank 0:: Total entries: 20
Rank 0:: Total entries: 20
Rank 0:: Total entries: 20
Rank 0:: Total entries: 20
Rank 0:: Total entries: 20
Rank 0:: Total entries: 20
Rank 0:: Total entries: 20
Rank 0:: Total entries: 20
Rank 0:: Total entries: 20
Rank 0:: Total entries: 20
```

Perhaps related to the recent communicator re-shuffle @JDBetteridge?

**Comment by JDBetteridge** [comment] 2022-12-06 11:56
Okay, this looks like we aren't honouring the contract to only use the internal comm for communication. Thanks for the MFE, I will investigate

**Comment by sghelichkhani** [comment] 2022-12-07 06:28
Just a word of caution that there seems to be objects both on `self._problem.u.function_space().mesh()._comm` and `self._problem.u.function_space().mesh().comm`. Using the proposed fix by Angus and changing `PETSc.garbage_view(comm=mesh.comm)` to  `PETSc.garbage_view(comm=mesh._comm)` in his reproducer I get:

```Rank 0:: Total entries: 17
Rank 0:: Total entries: 31
Rank 0:: Total entries: 49
Rank 0:: Total entries: 62
Rank 0:: Total entries: 79
Rank 0:: Total entries: 92
Rank 0:: Total entries: 109
Rank 0:: Total entries: 340
Rank 0:: Total entries: 358
Rank 0:: Total entries: 376

**Comment by JDBetteridge** [comment] 2022-12-07 14:39
Thanks for this, I'm closer to a full solution:

One part was due to a bad fix that accidentally got merged and has now been reverted.

Another should hopefully be fixed on [this](https://github.com/firedrakeproject/firedrake/pull/2674) branch, please check it out and report any further issues

**Closed** 2023-01-18 16:47 UTC
