### ISSUE TITLE
Firedrake install problem

### ISSUE THREAD

**Issue by dbojanjac** [firedrakeproject/firedrake#2041] opened 2021-04-27 07:28 UTC
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6379947/firedrake-install.log)

I have some problems installing firedrake on apple M1 mini. This is place where it stops.

File "/opt/homebrew/Cellar/python@3.9/3.9.4/Frameworks/Python.framework/Versions/3.9/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/Users/dario/Documents/projekti/python/firedrake/firedrake_env/bin/python', '-m', 'pip', 'install', '--no-build-isolation', '--no-binary', 'mpi4py,randomgen,islpy,numpy,scipy', '-vvv', 'https://github.com/firedrakeproject/VTKPythonPackage/releases/download/firedrake_20210113/ vtk-9.0.1-cp39-cp39-macosx_11_0_arm64.whl']' returned non-zero exit status 2.

**Comment by dham** [comment] 2021-04-27 08:35
OK so the critical line is this one:
```
AssertionError: 'vtk' != ' vtk' for wheel
```
Which is kind of funny. It implies that the vtk wheel (which we build) has a spurious space somewhere. @JDBetteridge: any idea?

**Comment by JDBetteridge** [comment] 2021-04-27 09:06
Looks like a spurious space was introduced in  https://github.com/firedrakeproject/firedrake/blob/efb48f4f178ae4989c146640025641cf0cc00a0e/scripts/firedrake-install#L1541

I'll open a PR to fix, in the mean time you can just remove the whitespace at the start of the string on line 154:
```python
source += "vtk-9.0.1-cp39-cp39-macosx_11_0_arm64.whl"
```

**Comment by dham** [comment] 2021-04-27 10:46
I've merged that PR, so if you download a new `firedrake-install` then this should be fixed. Please let me know if that works.

**Comment by dbojanjac** [comment] 2021-04-28 07:13
[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6389789/firedrake-install.log)

Sorry for late response. Now installation passes without errors but it cannot pass any test.

**Comment by dham** [comment] 2021-04-28 08:47
OK, can you run:
```
pytest tests/regression -x
```
That should give us the output of one failing test. Please post the output.

**Comment by dbojanjac** [comment] 2021-04-28 11:15
I tried python3 -c "import firedrake" and that works. Input  pytest tests/regression -x produces

[output.txt](https://github.com/firedrakeproject/firedrake/files/6391378/output.txt)

**Comment by wence-** [comment] 2021-04-28 11:16
Can you show the contents of `/Users/dario/virtualke/firedrake_env/.cache/pyop2/d9/ec262320a4a18051762c38bd33a189_p69786.err` ?

**Comment by dbojanjac** [comment] 2021-04-28 11:20
vim ec262320a4a18051762c38bd33a189_p69786.err gives 
**clang: error: the clang compiler does not support '-march=native'**

**Comment by wence-** [comment] 2021-04-28 11:29
OK, we need better automagic compiler flags for ARM-based systems. Which should happen in PyOP2.

Can you edit `/Users/dario/virtualke/firedrake_env/src/PyOP2/pyop2/compilation.py` line 371 (which is in the `MacCompiler` class) to remove `-march=native` and try?

We should then figure out how to detect that we're running on ARM.

**Comment by dbojanjac** [comment] 2021-04-28 12:02
Thnx. Now it is possible to start tests. I started pytest tests/regression -x and some tests are passed and some are not.
[output2.txt](https://github.com/firedrakeproject/firedrake/files/6391632/output2.txt)

**Comment by wence-** [comment] 2021-04-28 13:09
`tests/regression/test_aw.py F` This failure is I think not too concerning. We have had some issues in the past with it. The numerical conditioning of the Arnold-Winther elements is not good, and I can fully believe that on a completely different architecture to the ones we have previously tested on that the the compiler generates code that produces slightly different results.

If I look at the convergence of the problem:

```
  0 SNES Function norm 1.946318796695e+01 
  1 SNES Function norm 3.107821525035e-01 
  2 SNES Function norm 2.197495871656e-02 
  3 SNES Function norm 2.777067788787e-03 
  4 SNES Function norm 4.880452341946e-04 
  5 SNES Function norm 8.003239270821e-05 
  6 SNES Function norm 1.577838245499e-05 
  7 SNES Function norm 1.638502295233e-06 
  8 SNES Function norm 2.649193100902e-07 
  9 SNES Function norm 3.842382872243e-08 
 10 SNES Function norm 5.652642202803e-09 
```
We see that convergence is good, except that we set an upper limit of 10 iterations. If you run without `-x` then the full tests suite will run, it would be good to see if there are other failures.

**Comment by dbojanjac** [comment] 2021-04-28 13:36
Yeah, you are right. I tried some other solvers and my older codes and it seems that everything works fine.
Thank you for helping me with this issue. There is no way that I would be able to overcome this alone.

**Closed** 2021-04-28 14:07 UTC
