### ISSUE TITLE
Error when adding ufl.Zero to Function defined on Real elements

### ISSUE THREAD

**Issue by sebastkm** [firedrakeproject/firedrake#1141] opened 2017-09-14 13:20 UTC
I don't know if this is supposed to be supported, but the following code block
```
mesh = IntervalMesh(10, 0, 1)
V = FunctionSpace(mesh, "R", 0)
f = Function(V)
f += 0*f

# or
v = TestFunction(V)
g = assemble(v*dx)
g += 0*f
```
produces
`AttributeError: 'NoneType' object has no attribute '_extruded'`

**Comment by dham** [comment] 2017-09-14 13:40
Definitely a bug. Please file an issue and I’ll look at it when my normal life resumes after the H2020 deadline on 26 September


On 14 Sep 2017, at 14:20, Sebastian Mitusch <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't know if this is supposed to be supported, but the following code block

mesh = IntervalMesh(10, 0, 1)
V = FunctionSpace(mesh, "R", 0)
f = Function(V)
f += 0*f

# or
v = TestFunction(V)
g = assemble(v*dx)
g += 0*f


produces
AttributeError: 'NoneType' object has no attribute '_extruded'

**Comment by danshapero** [comment] 2020-04-09 17:56
I'm closing this issue because I can't reproduce it on a recent install of Firedrake.

**Closed by danshapero** 2020-04-09 17:56 UTC
Labels: bug
