### ISSUE TITLE
DG0 surface integrals

### ISSUE THREAD

**Issue by dmculley** [firedrakeproject/firedrake#825] opened 2016-07-14 12:19 UTC
Hello,

Doing a surface integral in P0 is kicking up the following error:

`ValueError: Buffer has wrong number of dimensions (expected 2, got 1)`

Minimal example
----------------------
```
from firedrake import *

mesh = UnitSquareMesh(10, 10)
V = FunctionSpace(mesh, 'DG', 0)
v = TestFunction(V)
u = TrialFunction(V)

a = u * v
assemble(a * ds)
```

**Comment by wence-** [comment] 2016-07-14 12:22
I can't reproduce this.  Can you show the backtrace?

**Comment by dmculley** [comment] 2016-07-14 12:51
That's embarassing, sorry should have run it first - it seems to be the bc on a different function that's causing it...

```
from firedrake import *

mesh  = UnitSquareMesh(10, 10)
B     = FunctionSpace(mesh, 'DG', 0)
v_b   = TestFunction(B)
b     = TrialFunction(B)
alpha = Function(B, name='Masking function')

alpha.assign(Constant(1))
alpha_bc = DirichletBC(B, Constant(0), 1)
alpha_bc.apply(alpha) 

a = v_b * b * ds
A = assemble(a)
```

**Comment by wence-** [comment] 2016-07-14 13:15
Thanks, this was a slightly subtle bug that is fixed in the referenced branch.  I'll wait for travis then merge.

**Comment by dmculley** [comment] 2016-07-14 13:16
Thanks muchly

**Closed** 2016-07-14 15:39 UTC

**Comment by wence-** [comment] 2016-07-14 16:02
Update firedrake and this should work.
