### ISSUE TITLE
Firedrake-install fails - blaslapack directory

### ISSUE THREAD

**Issue by sentz2** [firedrakeproject/firedrake#2124] opened 2021-06-23 19:52 UTC
Trying to install Firedrake on a macOS Catalina 10.15.7.  The installation fails when installing PTScotch.

It appears that it doesn't like the directory that Homebrew installs openblas into.

`You set a value for --with-blaslapack-dir=<dir>, but /usr/local/opt/openblas cannot be used`

[firedrake-install.log](https://github.com/firedrakeproject/firedrake/files/6704509/firedrake-install.log)
[configure.log](https://github.com/firedrakeproject/firedrake/files/6704511/configure.log)

**Comment by sentz2** [comment] 2021-06-24 00:20
Firedrake is installed successfully when I run

`python3 firedrake-install --with-blas=download`

However, I notice that the demo 'burgers.py' fails when I try to run it.  The solve fails to converge after 1 nonlinear iteration due to DIVERGED_DTOL.

Since this demo has worked for me on other machines, I am worried that there might still be something wrong with the PETSc installation.

**Comment by connorjward** [comment] 2021-06-24 16:29
We believe that this is an upstream issue with PETSc that we only encountered a few days ago when our fork got updated. 

In the meantime a simple solution could be to use an older PETSc version. I've created a branch for this so you should be able to run:

```$ python3 firedrake-install --package-branch petsc temporary-revert-2124```

@sv2518 @JDBetteridge can you provide an update?

**Comment by sv2518** [comment] 2021-06-24 18:18
The issue is now reported here on the petsc side, see https://gitlab.com/petsc/petsc/-/issues/948

**Comment by connorjward** [comment] 2021-06-28 12:28
There's an upstream fix that hasn't yet been merged. The issue above says that you could try `--with-blas=/usr/local/opt/openblas/lib` as a workaround for now.

**Comment by connorjward** [comment] 2021-06-30 16:05
Closing as this should now be fixed.

**Closed by connorjward** 2021-06-30 16:05 UTC
