### ISSUE TITLE
Test Case for the Observation Operator Functionality

### ISSUE THREAD

**Issue by alsgregory** [firedrakeproject/firedrake#651] opened 2015-12-08 14:43 UTC
Hi Miklos,

Here is the GIST link for the testing case that will test if the extra functionality for deriving distances between observation (at arbitrary coordinates) operator against a firedrake function is working.

https://gist.github.com/anonymous/0a67c9955cc1771432bc

Ali Gregory

**Comment by wence-** [comment] 2015-12-08 14:49
Hi Ali,

can you rework this in the style of one of the actual firedrake tests?  Add a file in `tests/regression/` called `test_SOME_NAME.py` with a function called `test_SOME_THING` that uses normal python assertions to check if things are working.

**Comment by miklos1** [comment] 2015-12-08 14:52
I also suggest you to get the latest version of Firedrake, as you seem to be still using an outdated API from an old development version.

**Comment by alsgregory** [comment] 2015-12-09 10:20
Thanks both of you. I'll change it now and add it to tests/regression. Miklos what should I use as the name of the function that you are designing for us? And the inputs to it / distance output etc. Many Thanks,
Ali

**Comment by alsgregory** [comment] 2015-12-10 11:08
Hi Miklos, the new test cases can be found here. 

https://gist.github.com/alsgregory/612f43cb2e178385210e

It is currently unopearational due to the fact that the function to test is not defined. Should I still add it to the tests/regression directory?

**Comment by wence-** [comment] 2015-12-10 11:16
Yes, please make a branch in your fork of firedrake, add the test, and propose it as a pull request.  Because the tests are expected to fail due to the functionality not being implemented yet, you can mark them as such:

```python
import pytest
...

@pytest.mark.xfail(reason="Waiting for missing functionality")
def test_foo(...):
    ...
```

This way, things will get run, including code linting and so forth.

**Comment by miklos1** [comment] 2016-01-08 14:48
Closing, since #665.

**Closed by miklos1** 2016-01-08 14:48 UTC
