### ISSUE TITLE
More assembly cache breakage

### ISSUE THREAD

**Issue by dorugeber** [firedrakeproject/firedrake#609] opened 2015-10-12 13:24 UTC
```
from firedrake import *

# parameters["assembly_cache"]["enabled"] = False

mesh = UnitSquareMesh(10, 10)

V = FunctionSpace(mesh, "CG", 1)

m = Function(V).interpolate(Expression("0.5"))

print "Before:", assemble(m*dx)
m.dat.data[:] /= assemble(m*dx)
print "After:", assemble(m*dx)
```

Assembly cache enabled:

```
andrew@ubuntu:~$ python assemblycache_bork.py 
Before: 0.5
After: 0.5
```

Assembly cache disabled:

```
andrew@ubuntu:~$ python assemblycache_bork.py 
Before: 0.5
After: 1.0
```

However, this following _does_ work with assembly cache enabled:

```
foo = assemble(m*dx)
print "Before:", foo
m.dat.data[:] /= foo
print "After:", assemble(m*dx)
```

**Comment by wence-** [comment] 2016-02-16 10:48
This is *really* subtle.

The dat versioning is working correctly.  However, because you're using `/=`, the lvalue property is evaluated before the rvalue assemble call.  As a result, the assembly sees the "new" dat version and the subsequent call to assembly thinks the cache is valid.  I don't know how to fix this, because I can't work around the semantics of the language.

**Comment by miklos1** [comment] 2016-02-16 10:51
We should probably find a way to disable (deprecate?) this broken syntax then.

**Comment by wence-** [comment] 2016-02-16 10:53
Unfortunately, directly modifying the data array like this is sort of part of the "semi-public" API.

**Comment by miklos1** [comment] 2016-02-16 10:55
Well, if we can't fix this syntax, then I argue this semi-public API should change. If users might be relying on this already, then we should start with deprecation, using ugly warnings and suggestions about the correct syntax to use.

**Comment by dorugeber** [comment] 2016-02-16 10:58
> As a result, the assembly sees the "new" dat version and...
Wait, what new dat version?  It hasn't been modified yet, or maybe I misunderstand you.

**Comment by wence-** [comment] 2016-02-16 11:05
`m.dat.data` accesses the Dat with RW semantics, so that property bumps that Dat version.  Normally, the lvalue is evaluated after the rvalue, so you would expect to evaluate assemble(m*dx) first (seeing the old version), then access the data array, updating the version.

What actually happens is, access the data array, updating the version, then evaluate assemble(m*dx) seeing a new version (but the same data values) store the result with the *new* version.  Now change the values (not modifying the version again).  So now the version in the assembly cache doesn't match the data.

**Comment by miklos1** [comment] 2016-02-16 11:10
Maybe we could make PyOP2 `Dat` [ACID](https://en.wikipedia.org/wiki/ACID) instead of just having an *ad hoc* versioning?

**Comment by wence-** [comment] 2016-02-16 11:58
Maybe.  However, that doesn't fix things per se, because the problem is not the Dat versioning in this case, but how the versioning interfaces with the pyhton you do underneath.

**Comment by wence-** [comment] 2016-02-16 11:59
Andrew, I note as well, you can write `m.dat /= assemble(m*dx)` instead.

**Comment by miklos1** [comment] 2016-02-16 12:00
It could help detecting these cases and reporting an error instead of producing a borked result.

**Comment by wence-** [comment] 2016-11-03 17:28
Closed by virtue of removing the assembly cache.

**Closed by wence-** 2016-11-03 17:28 UTC
