### ISSUE TITLE
loopy or pyopencl fails to install perhaps related to pybind11 

### ISSUE THREAD

**Issue by steverweber** [firedrakeproject/firedrake#1450] opened 2019-06-06 13:08 UTC
somewhat related to:
https://github.com/firedrakeproject/firedrake/issues/1431

have a fail during install perhaps related to `pybind11` or I simply need to apt install something before installing firedrake.

```
apt -y install libjs-excanvas mercurial-common python3-venv

ALIAS_FD=firedrake-full
rm -rf /opt/$ALIAS_FD
mkdir /opt/$ALIAS_FD
cd /opt/$ALIAS_FD

curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/complex/scripts/firedrake-install
env -u PYTHONPATH python3 firedrake-install --disable-ssh --cache-dir=/tmp/$ALIAS_FD \
   --slepc --install gusto --install thetis --install pyadjoint --install icepack
```

tail of stdout
```
Depending on your platform, may take between a few minutes and an hour or more to build!
Installing pip dependencies for petsc4py
No dependencies found. Skipping.
Installing pip dependencies for COFFEE
Installing pip dependencies for loopy
Traceback (most recent call last):
  File "firedrake-install", line 1203, in <module>
    pip_requirements(p)
  File "firedrake-install", line 647, in pip_requirements
    run_pip_install(["-r", "%s/requirements.txt" % package])
  File "firedrake-install", line 618, in run_pip_install
    check_call(pipinstall + pipargs)
  File "firedrake-install", line 456, in check_call
    log.debug(subprocess.check_output(arguments, stderr=subprocess.STDOUT, env=env).decode())
  File "/usr/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['/opt/firedrake-full/firedrake/bin/python', '-m', 'pip', 'install', '--no-binary', 'mpi4py', '-vvv', '-r', 'loopy/requirements.txt']' returned non-zero exit status 1.
```

most of the tail end of `/opt/firedrake-full/firedrake-install.log`
```
  Running setup.py install for cgen: finished with status 'done'
  Removing source in /tmp/pip-req-build-2b8s3_zz
  Created temporary directory: /tmp/pip-record-_rzqk58r
  Running setup.py install for pyopencl: started
    Running command /opt/firedrake-full/firedrake/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-_tllk1wg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)
(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_rzqk58r/install-record.txt --single-ver
sion-externally-managed --compile --install-headers /opt/firedrake-full/firedrake/include/site/python3.6/pyopencl
    ---------------------------------------------------------------------------
    Pybind11 is not installed.
    ---------------------------------------------------------------------------
    Very likely, the build process after this message will fail.

    Simply press Ctrl+C and type
    python -m pip install pybind11
    to fix this. If you don't, the build will continue
    in a few seconds.

    [1] https://pybind11.readthedocs.io/en/stable/
    ---------------------------------------------------------------------------
    Continuing in 10 seconds...   ^M    Continuing in 9 seconds...   ^M    Continuing in 8 seconds...   ^M    Continuing in 7 seconds...   ^M    Continuing in 6 seconds...   ^M    Continuing in 5 seconds...   ^M    Continuing in 4 seconds...   ^M    Continuing in 3 seconds...   ^M    Continuing in 2 seconds...   ^M    Continuing in 1 seconds...
    ---------------------------------------------------------------------------
    Mako is not installed.
    ---------------------------------------------------------------------------
    That is not a problem, as most of PyOpenCL will be just fine
    without it. Some higher-level parts of pyopencl (such as
    pyopencl.reduction) will not function without the templating engine
    Mako [1] being installed. If you would like this functionality to
    work, you might want to install Mako after you finish
    installing PyOpenCL.

    Simply type
    python -m pip install mako
    either now or after the installation completes to fix this.

    [1] http://www.makotemplates.org/
    ---------------------------------------------------------------------------
    Hit Ctrl-C now if you'd like to think about the situation.
    ---------------------------------------------------------------------------
    Continuing in 5 seconds...   ^M    Continuing in 4 seconds...   ^M    Continuing in 3 seconds...   ^M    Continuing in 2 seconds...   ^M    Continuing in 1 seconds...
    running install
...

    copying pyopencl/cl/pyopencl-random123/philox.cl -> build/lib.linux-x86_64-3.6/pyopencl/cl/pyopencl-random123
    copying pyopencl/cl/pyopencl-random123/threefry.cl -> build/lib.linux-x86_64-3.6/pyopencl/cl/pyopencl-random123
    running build_ext
    creating tmp
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -O3 -DNDEBUG -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/firedrake-full/firedrake/i
nclude -I/usr/include/python3.6m -c /tmp/tmpn379ydu6.cpp -o tmp/tmpn379ydu6.o -std=gnu++14
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -O3 -DNDEBUG -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -I/opt/firedrake-full/firedrake/i
nclude -I/usr/include/python3.6m -c /tmp/tmpin526kd4.cpp -o tmp/tmpin526kd4.o -fvisibility=hidden
    building 'pyopencl._cl' extension
    creating build/temp.linux-x86_64-3.6
    creating build/temp.linux-x86_64-3.6/src
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -O3 -DNDEBUG -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYGPU_PACKAGE=pyopencl -DPYGPU_PYOPENCL=1 -Ipybind11/include -I/opt/firedrake-full/firedrake/include/site/python3.6 -I/opt/firedrake-full/firedrake/include/site/python3.6 -I/opt/firedrake-full/firedrake/lib/python3.6/site-packages/numpy/core/include -I/opt/firedrake-full/firedrake/include -I/usr/include/python3.6m -c src/wrap_constants.cpp -o build/temp.linux-x86_64-3.6/src/wrap_constants.o -fvisibility=hidden -DVERSION_INFO="2018.2.5" -std=gnu++14 -fvisibility=hidden
    In file included from /opt/firedrake-full/firedrake/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                     from /opt/firedrake-full/firedrake/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /opt/firedrake-full/firedrake/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from src/numpy_init.hpp:32,
                     from src/wrap_cl.hpp:87,
                     from src/wrap_constants.cpp:27:
    /opt/firedrake-full/firedrake/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    In file included from src/wrap_constants.cpp:27:0:
    src/wrap_cl.hpp: In constructor ‘pyopencl::command_queue::command_queue(const pyopencl::context&, const pyopencl::device*, pybind11::object)’:
    src/wrap_cl.hpp:1325:13: warning: unused variable ‘hex_plat_version’ [-Wunused-variable]
             int hex_plat_version = ctx.get_hex_platform_version();
                 ^~~~~~~~~~~~~~~~
    src/wrap_cl.hpp: In constructor ‘pyopencl::sampler::sampler(const pyopencl::context&, bool, cl_addressing_mode, cl_filter_mode)’:
    src/wrap_cl.hpp:3676:13: warning: unused variable ‘hex_plat_version’ [-Wunused-variable]
             int hex_plat_version = ctx.get_hex_platform_version();
                 ^~~~~~~~~~~~~~~~
    x86_64-linux-gnu-gcc -pthread -fwrapv -Wall -O3 -DNDEBUG -g -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -fPIC -DPYGPU_PACKAGE=pyopencl -DPYGPU_PYOPENCL=1 -Ipybind11/include -I/opt/firedrake-full/firedrake/include/site/python3.6 -I/opt/firedrake-full/firedrake/include/site/python3.6 -I/opt/firedrake-full/firedrake/lib/python3.6/site-packages/numpy/core/include -I/opt/firedrake-full/firedrake/include -I/usr/include/python3.6m -c src/wrap_cl.cpp -o build/temp.linux-x86_64-3.6/src/wrap_cl.o -fvisibility=hidden -DVERSION_INFO="2018.2.5" -std=gnu++14 -fvisibility=hidden
    In file included from /opt/firedrake-full/firedrake/lib/python3.6/site-packages/numpy/core/include/numpy/ndarraytypes.h:1822:0,
                     from /opt/firedrake-full/firedrake/lib/python3.6/site-packages/numpy/core/include/numpy/ndarrayobject.h:12,
                     from /opt/firedrake-full/firedrake/lib/python3.6/site-packages/numpy/core/include/numpy/arrayobject.h:4,
                     from src/numpy_init.hpp:32,
                     from src/wrap_cl.hpp:87,
                     from src/wrap_cl.cpp:27:
    /opt/firedrake-full/firedrake/lib/python3.6/site-packages/numpy/core/include/numpy/npy_1_7_deprecated_api.h:17:2: warning: #warning "Using deprecated NumPy API, disable it with " "#define NPY_NO_DEPRECATED_API NPY_1_7_API_VERSION" [-Wcpp]
     #warning "Using deprecated NumPy API, disable it with " \
      ^~~~~~~
    In file included from src/wrap_cl.cpp:27:0:
    src/wrap_cl.hpp: In constructor ‘pyopencl::command_queue::command_queue(const pyopencl::context&, const pyopencl::device*, pybind11::object)’:
    src/wrap_cl.hpp:1325:13: warning: unused variable ‘hex_plat_version’ [-Wunused-variable]
             int hex_plat_version = ctx.get_hex_platform_version();
                 ^~~~~~~~~~~~~~~~
    src/wrap_cl.hpp: In constructor ‘pyopencl::sampler::sampler(const pyopencl::context&, bool, cl_addressing_mode, cl_filter_mode)’:
    src/wrap_cl.hpp:3676:13: warning: unused variable ‘hex_plat_version’ [-Wunused-variable]
             int hex_plat_version = ctx.get_hex_platform_version();
                 ^~~~~~~~~~~~~~~~
    src/wrap_cl.cpp: At global scope:
    src/wrap_cl.cpp:42:16: error: expected constructor, destructor, or type conversion before ‘(’ token
     PYBIND11_MODULE(_cl, m)


    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
  Running setup.py install for pyopencl: finished with status 'error'
Cleaning up...
  Removing source in /tmp/pip-req-build-_tllk1wg
  Removing source in /tmp/pip-req-build-ccyrs1qk
  Removing source in /tmp/pip-req-build-r3kq02l2
  Removing source in /tmp/pip-req-build-fs9ye38l
  Removing source in /tmp/pip-req-build-8y__vjx7
Removed build tracker '/tmp/pip-req-tracker-uud1swct'
ERROR: Command "/opt/firedrake-full/firedrake/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-_tllk1wg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_rzqk58r/install-record.txt --single-version-externally-managed --compile --install-headers /opt/firedrake-full/firedrake/include/site/python3.6/pyopencl" failed with error code 1 in /tmp/pip-req-build-_tllk1wg/
Exception information:
Traceback (most recent call last):
  File "/opt/firedrake-full/firedrake/lib/python3.6/site-packages/pip/_internal/cli/base_command.py", line 178, in main
    status = self.run(options, args)
  File "/opt/firedrake-full/firedrake/lib/python3.6/site-packages/pip/_internal/commands/install.py", line 414, in run
    use_user_site=options.use_user_site,
  File "/opt/firedrake-full/firedrake/lib/python3.6/site-packages/pip/_internal/req/__init__.py", line 58, in install_given_reqs
    **kwargs
  File "/opt/firedrake-full/firedrake/lib/python3.6/site-packages/pip/_internal/req/req_install.py", line 951, in install
    spinner=spinner,
  File "/opt/firedrake-full/firedrake/lib/python3.6/site-packages/pip/_internal/utils/misc.py", line 776, in call_subprocess
    % (command_desc, proc.returncode, cwd))
pip._internal.exceptions.InstallationError: Command "/opt/firedrake-full/firedrake/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-_tllk1wg/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-_rzqk58r/install-record.txt --single-version-externally-managed --compile --install-headers /opt/firedrake-full/firedrake/include/site/python3.6/pyopencl" failed with error code 1 in /tmp/pip-req-build-_tllk1wg/

```

**Comment by dham** [comment] 2019-06-06 14:50
Does this still fail if you install using the instructions from: https://github.com/firedrakeproject/firedrake/projects/4
Note that particular TSFC and PyOP2 branches are specified.

**Comment by wence-** [comment] 2019-06-06 15:13
I think we need to back-port the relevant part of the loopy changes to firedrake-install. See here https://github.com/firedrakeproject/firedrake/commit/00e289ec39920b97146eb8f0355bfc3b59282213#diff-3079eb76bd263400f953f2fd85a803ec

The issue is that loopy optionally specifies pyopencl etc... in requirements.txt, but firedrake-install picks that up in the complex branch (we skip over it in the master branch).

**Comment by steverweber** [comment] 2019-06-06 16:01
@dham complex branch failed yesterday when I tried it.
I then tried the default branch and still no luck.

@wence-  This looks like it will do the job, should I wait for the backport or is master stable to use for a classroom of students?

Thanks for the quick help!

**Comment by dham** [comment] 2019-06-06 16:05
Master is stable and is definitely what you should be using in class.

Master doesn't support complex - complex is still very much in beta and it would be a brave lecturer indeed who ran a whole class exercise on the complex branch!

**Comment by dham** [comment] 2019-06-06 16:07
> @dham complex branch failed yesterday when I tried it.
> I then tried the default branch and still no luck.

I think I don't understand this comment. The advice I was trying to give was to use the specific instructions on the complex project page. These install older versions of some components which should avoid the issue you were observing. As far as I can see from your install line above, you weren't using those.

**Comment by steverweber** [comment] 2019-06-06 16:29
yesterday i used
```
env -u PYTHONPATH python3 firedrake-install --disable-ssh --cache-dir=/tmp/$ALIAS_FD --slepc --complex --package-branch firedrake complex --install gusto
```

i'll try this now.
``
python3 firedrake-install --complex --package-branch tsfc 6e5a51b87e73739e9d854b4df9b2cb19b08f45f9 --package-branch PyOP2 34205db46d8f659d8186fb420891c0d8ab228171 --package-branch firedrake complex --install gusto
```

**Comment by steverweber** [comment] 2019-06-06 17:19
success with
```
ALIAS_FD=firedrake-complex-full
rm -rf /opt/$ALIAS_FD
mkdir /opt/$ALIAS_FD
cd /opt/$ALIAS_FD

curl -O https://raw.githubusercontent.com/firedrakeproject/firedrake/complex/scripts/firedrake-install
env -u PYTHONPATH python3 firedrake-install --disable-ssh --cache-dir=/tmp/$ALIAS_FD --slepc \
    --complex \
    --package-branch tsfc 6e5a51b87e73739e9d854b4df9b2cb19b08f45f9 \
    --package-branch PyOP2 34205db46d8f659d8186fb420891c0d8ab228171 \
    --package-branch firedrake complex \
    --install gusto --install thetis --install pyadjoint --install icepack
```

thanks for the quick fix

**Comment by wence-** [comment] 2019-06-07 11:27
OK, thanks, I'll close the issue.

**Closed by wence-** 2019-06-07 11:27 UTC
