### ISSUE TITLE
Issue with code generation from SLATE

### ISSUE THREAD

**Issue by mc4117** [firedrakeproject/firedrake#2076] opened 2021-05-17 10:05 UTC
After the new firedrake loopy sprint, firedrake is often throwing the error 

>           raise RuntimeError("split_term expects a multiplicative term")
[2021-05-14T13:12:04.425Z] E           RuntimeError: split_term expects a multiplicative term

This means that `thetis` does not run with the new firedrake. Below is a minimum failing example for this probem
```
from firedrake import *
mesh = UnitTriangleMesh()
V = FunctionSpace(mesh, "DG", 0)
Q = V*V
u, _ = TrialFunctions(Q)
v, _ = TestFunctions(Q)
a = u*v*dx
A = Tensor(a)
Ainv = A.inv
assemble(Ainv)
```
I have been told this issue is to do with code generation in SLATE.

**Comment by sv2518** [comment] 2021-05-17 10:27
Hi Mariana, I have just looked at the minimal failing example. I don't get the same error as in Thetis when I run it. Reason for that is that the A in the example is a singular matrix.

**Comment by wence-** [comment] 2021-05-17 10:31
Can you try with `firedrake-clean`? This reliably produces the `split_term` error. I think the issue is that loopy has introduced error checking that subarrayref nodes line up, but it can't handle the `//` that some part of our pipeline puts in.

**Comment by mc4117** [comment] 2021-05-17 10:34
Hmm that's odd. Does this example work for you too @sv2518 ? 
```
from thetis import *

lx = 5e3
ly = 1e3
mesh2d = RectangleMesh(10, 1, lx, ly)

# bathymetry
p1_2d = get_functionspace(mesh2d, 'CG', 1)
bathymetry_2d = Function(p1_2d, name="bathymetry")
bathymetry_2d.assign(100.0)

n = 1  # number of timesteps
dt = 1000.

solver_obj = solver2d.FlowSolver2d(mesh2d, bathymetry_2d)
solver_obj.options.simulation_end_time = n*dt
solver_obj.options.timestep = dt

solver_obj.assign_initial_conditions(uv=Constant((1.0, 0.0)))

solver_obj.iterate()
```

**Comment by sv2518** [comment] 2021-05-17 11:20
> I think the issue is that loopy has introduced error checking that subarrayref nodes line up, but it can't handle the // that some part of our pipeline puts in.

Yes, that seems to be the issue. I will raise it to the loopy people. I think they need to introduce a map_floordiv on one of the pymbolic mappers, but I don't understand this well enough to know in which of them. Since we are assuring that our kernels line up with our matching function in PyOP2, we could disable this line https://github.com/firedrakeproject/loopy/blob/0fd29225258820ffa78cd90f0e672906143e6252/loopy/translation_unit.py#L840 until it is fixed on their side.

**Comment by mc4117** [comment] 2021-05-17 11:34
I can confirm that if this line is commented out then the tests pass on the thetis side

**Comment by sv2518** [comment] 2021-05-17 11:59
I have opened an issue in loopy here https://github.com/inducer/loopy/issues/366

**Closed** 2021-05-17 18:32 UTC
